site_name: Algovis
site_author: Mayank
copyright: © Copyright 2020, Mayank Arora

repo_url: https://github.com/hotshot07/algovis
edit_uri: edit/master/docs/docs/

nav:

    - Home: 'index.md'
    - Installing: 'installing.md'
    - Sorting: 'sorting.md'
    - Searching: 'searching.md'
    - License : 'about/license.md'
    - Author: 'about/about.md'

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: green
  favicon: img/favicon.ico
  logo: img/favicon.ico
  google_analytics:
    - UA-149605585-2
    - auto

markdown_extensions:
  - codehilite