site_name: Algovis
site_author: Mayank
copyright: © Copyright 2020, Mayank Arora

repo_url: https://github.com/hotshot07/algovis
edit_uri: edit/master/docs/docs/

nav:
    - Algovis:
      - Home: 'index.md'
      - Installing: 'installing.md'
    - Sorting:
      - Bubble Sort: 'sorting/bubblesort.md'
      - Insertion Sort: 'sorting/insertionsort.md'
      - Selection Sort: 'sorting/selectionsort.md'
      - Merge Sort: 'sorting/mergesort.md'
      - Quick Sort: 'sorting/quicksort.md'
    - Searching:
      - Linear Search: 'searching/linearsearch.md'
      - Binary Search: 'searching/binarysearch.md'
    - About:
      - Author: 'about/about.md'
      - License : 'about/license.md'

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light blue
  favicon: img/favicon.ico
  logo: img/favicon.ico
  google_analytics:
    - UA-149605585-2
    - auto

markdown_extensions:
  - codehilite